### ISSUE TITLE
【已发放】审核 WTF Rust 前19讲

### ISSUE THREAD

**Issue by AmazingAng** [WTFAcademy/WTF-Rust#6]
审核 WTF Rust 教程前19讲： https://github.com/WTFAcademy/WTF-Rust

先决条件: 需要熟悉Rust。

每人最多认领3讲。

任务奖励：300 USDC，根据贡献分配。

审核进度：

1. Hello Rust  [zhiyuan2007](https://github.com/zhiyuan2007)
2. 基本类型  [zhiyuan2007](https://github.com/zhiyuan2007)
3. 复合类型  [keienWang](https://github.com/keienWang)
4. 结构体，枚举  [keienWang](https://github.com/keienWang)
5. 所有权、借用、引用  [keienWang](https://github.com/keienWang)
6. 函数  [buttonwild](https://github.com/buttonwild)
7. Rust 测试  [buttonwild](https://github.com/buttonwild)
8. 集合类型  [buttonwild](https://github.com/buttonwild)
9. 错误处理  [yjshi2015](https://github.com/yjshi2015)
10. Trait  [Skytrc](https://github.com/Skytrc)
11. 泛型  [Skytrc](https://github.com/Skytrc)
12. 生命周期  [yjshi2015](https://github.com/yjshi2015)
13. Cargo  [0xb00lean](https://github.com/0xb00lean)
14. Rust 常用库  [0xb00lean](https://github.com/0xb00lean)
15. 线程  [JangoCCC](https://github.com/JangoCCC)
16. 通道  [JangoCCC](https://github.com/JangoCCC)
17. 锁  [zklim](https://github.com/zklim)
18. 异步编程  [zklim](https://github.com/zklim)
19. IO[zklim](https://github.com/zklim)

**Comment by zhiyuan2007** [comment]
1-2

**Comment by Skytrc** [comment]
10-11

**Comment by keienWang** [comment]
3-5

**Comment by buttonwild** [comment]
6-8

**Comment by yjshi2015** [comment]
9～11

**Comment by 0xb00lean** [comment]
13-14

**Comment by yjshi2015** [comment]
12

**Comment by zklim** [comment]
17-19

**Comment by JangoCCC** [comment]
15-16

**Comment by 54441384** [comment]
你们不给后面人留汤了啊。，。。

**Comment by clock015** [comment]
17

**Comment by VioletSakura777** [comment]
闹麻了，没领到

**Comment by raozhiyong11** [comment]
好快啊

**Comment by AmazingAng** [comment]
> 17-19

是不是忘记review了

**Comment by AmazingAng** [comment]
> 15-16


17-19

是不是忘记review了

**Comment by zklim** [comment]
> > 17-19
> 
> 是不是忘记review了

啊抱歉真忘了，明天会完成

**Comment by zklim** [comment]
> > 15-16
> 
> 17-19
> 
> 是不是忘记review了

审核好了 #20
